### PR TITLE
move the test code to use production APIs

### PR DESCRIPTION
**Pull request by xster**

### CODE REVIEW

**Comment by xster** [comment]
@gaaclarke I can't assign you in your repo

**Review by gaaclarke — APPROVED** [review]

**Review by gaaclarke — COMMENTED** [review]
@xster  Wait, don't we want a way to run the tests with a comparison to what we used to have?  It could be a runtime option now though.

**Comment by xster** [comment]
Sure. Do you think there might be a difference? Or is this just a thing switch in this file that the FlutterEngineGroup is now doing?

**Comment by gaaclarke** [comment]
> Sure. Do you think there might be a difference? Or is this just a thing switch in this file that the FlutterEngineGroup is now doing?

I was thinking to show the difference between using a FlutterEngineGroup versus not, which should translate to how things were before our multiple flutters work.

**Comment by xster** [comment]
ya you're right

**Pull request closed without merging**
